### ISSUE TITLE
"In This Article" Heirarchy

### ISSUE THREAD

**Issue by ryanpeach** [ansys/jekyll-theme-corp#7]
h1, h2, etc should show heirarchy on the sidebar:

<img width="912" alt="Screen Shot 2022-09-22 at 11 59 09 AM" src="https://user-images.githubusercontent.com/14838729/191796109-ad8c4c83-b840-432c-844c-860ff26bba5c.png">

**Comment by RVR06** [comment]
![image](https://user-images.githubusercontent.com/57908971/193859720-a54b0884-da36-40dd-bb26-26fa66eb0850.png)
